apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mocljudem
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: mocljudem
    newName: rg.fr-par.scw.cloud/djnd/mocljudem
    newTag: 'bcdb0945de9e41a02392bf768462573c54393d7f'
