apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mocljudem
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: mocljudem
    newName: rg.fr-par.scw.cloud/djnd/mocljudem
    newTag: 'a830169dec767b6cc4b29b128f858357df38e35f'
