apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mocljudem
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: mocljudem
    newName: rg.fr-par.scw.cloud/djnd/mocljudem
    newTag: 'ca6715006f7416c4b5d7124fae558b490a3da782'
