apiVersion: v1
kind: Secret
metadata:
  name: mocljudem-secrets
type: Opaque
stringData:
  DJANGO_DEBUG: ""
  DJANGO_SECRET_KEY: "changeme"
  DJANGO_STATIC_ROOT: "/storage/static"
  DJANGO_STATIC_URL_BASE: "https://files.mocljudem.si/static/"
  DJANGO_DATABASE_HOST: "changeme"
  DJANGO_DATABASE_PORT: "5432"
  DJANGO_DATABASE_NAME: "changeme"
  DJANGO_DATABASE_USER: "changeme"
  DJANGO_DATABASE_PASSWORD: "changeme"
  # DJANGO_ENABLE_S3: "yes"
  # DJANGO_AWS_ACCESS_KEY_ID: "changeme"
  # DJANGO_AWS_SECRET_ACCESS_KEY: "changeme"
  # DJANGO_SENTRY_URL: "changeme"
  # SENTRY_ENVIRONMENT: "production"
