# Generated by Django 6.0.8 on 2026-08-24 11:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Glavno besedilo, ki se prikaže v hero sekciji strani",
                null=True,
                verbose_name="Glavno besedilo",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text_source",
            field=models.CharField(
                blank=True,
                help_text="Malo besedilo, ki se prikaže pod glavnim besedilom v hero sekciji strani",
                max_length=255,
                null=True,
                verbose_name="Vir besedila",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="lead_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Opis, ki se prikaže pod hero sekcijo strani",
                null=True,
                verbose_name="Opis",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Slika, ki se prikaže v glavi strani",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logotip",
            ),
        ),
    ]
