# Generated by Django 6.0.8 on 2026-08-24 11:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_hero_text_homepage_hero_text_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="info_push",
            field=wagtail.fields.StreamField(
                [("button", 2), ("notice", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Besedilo na gumbu", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Povezava, kamor gumb vodi", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 1)]],
                        {"icon": "link", "label": "Gumb"},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Besedilo obvestila", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3)]],
                        {"icon": "doc-full", "label": "Obvestilo"},
                    ),
                },
                help_text="Elementi, ki so prikazani nad preostalo vsebino strani, npr. za obvestila ali akcije",
                null=True,
                verbose_name="Info push",
            ),
        ),
    ]
