# Generated by Django 6.0.8 on 2026-08-24 11:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_info_push"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="info_push",
            field=wagtail.fields.StreamField(
                [("button", 2), ("notice", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Besedilo na gumbu", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Povezava", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 1)]],
                        {"icon": "link", "label": "Gumb"},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Besedilo obvestila", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3)]],
                        {"icon": "doc-full", "label": "Obvestilo"},
                    ),
                },
                help_text="Elementi, ki so prikazani nad preostalo vsebino strani, npr. za obvestila ali akcije",
                null=True,
                verbose_name="Info push",
            ),
        ),
        migrations.CreateModel(
            name="CampaignPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Opis kampanje",
                        null=True,
                        verbose_name="Opis",
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("link", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Besedilo povezave", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Povezava, kamor vodi", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("url", 1)]],
                                {"icon": "link", "label": "Povezava"},
                            ),
                        },
                        help_text="Povezave pod naslovom in opisom kampanje",
                        null=True,
                        verbose_name="Povezave",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Slika kampanje",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Slika",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
