# Generated by Django 6.0.8 on 2026-08-24 13:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_homepage_info_push_campaignpage"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignpage",
            options={"verbose_name": "Kampanja", "verbose_name_plural": "Kampanje"},
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "verbose_name": "Domača stran",
                "verbose_name_plural": "Domače strani",
            },
        ),
        migrations.AlterField(
            model_name="campaignpage",
            name="links",
            field=wagtail.fields.StreamField(
                [("link", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Besedilo povezave", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Povezava, kamor vodi", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("text", 0), ("url", 1)]], {}),
                },
                help_text="Povezave pod naslovom in opisom kampanje",
                null=True,
                verbose_name="Povezave",
            ),
        ),
        migrations.CreateModel(
            name="TimelinePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "statuses",
                    wagtail.fields.StreamField(
                        [("status", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("empty", "Prazen"),
                                        ("blue", "Moder"),
                                        ("green", "Zelen"),
                                        ("yellow", "Rumen"),
                                        ("red", "Rdeč"),
                                        ("violet", "Vijoličen"),
                                    ]
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Naslov statusa", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Kratka besedilna oznaka, ki se prikaže pod naslovom",
                                    "label": "Besedilo statusa",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Opis statusa", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Besedilo povezave", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Povezava, kamor vodi", "required": True},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 4), ("url", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.StreamBlock",
                                [[("link", 6)]],
                                {"label": "Povezave", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("status_type", 0),
                                        ("title", 1),
                                        ("status_text", 2),
                                        ("description", 3),
                                        ("links", 7),
                                    ]
                                ],
                                {"icon": "radio-empty", "label": "Status"},
                            ),
                        },
                        help_text="Seznam statusov, ki se prikažejo v časovnici",
                        null=True,
                        verbose_name="Statusi",
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ikona časovnice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Ikona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Časovnica",
                "verbose_name_plural": "Časovnice",
            },
            bases=("wagtailcore.page",),
        ),
    ]
