# Generated by Django 6.0.8 on 2026-08-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_campaignpage_options_alter_homepage_options_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Slika, ki bo prikazana pri deljenju strani na socialnih omrežjih.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Meta slika",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Slika, ki bo prikazana pri deljenju strani na socialnih omrežjih.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Meta slika",
            ),
        ),
        migrations.AddField(
            model_name="timelinepage",
            name="meta_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Slika, ki bo prikazana pri deljenju strani na socialnih omrežjih.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Meta slika",
            ),
        ),
    ]
