# Generated by Django 6.0.8 on 2026-09-01 08:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_campaignpage_meta_image_homepage_meta_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelinepage",
            name="statuses",
            field=wagtail.fields.StreamField(
                [("status", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("empty", "Prazen"),
                                ("blue", "Moder"),
                                ("green", "Zelen"),
                                ("yellow", "Rumen"),
                                ("red", "Rdeč"),
                                ("violet", "Vijoličen"),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Naslov statusa", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Kratka besedilna oznaka, ki se prikaže pod naslovom",
                            "label": "Besedilo statusa",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Opis statusa", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Besedilo povezave", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Povezava, kamor vodi", "required": True},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("text", 4), ("url", 5)]], {}),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("link", 6)]],
                        {"label": "Povezave", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Prikaži status razširjen, namesto da ga uporabnik mora klikniti, da se razširi",
                            "label": "Razširi status",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("status_type", 0),
                                ("title", 1),
                                ("status_text", 2),
                                ("description", 3),
                                ("links", 7),
                                ("expanded", 8),
                            ]
                        ],
                        {"icon": "radio-empty", "label": "Status"},
                    ),
                },
                help_text="Seznam statusov, ki se prikažejo v časovnici",
                null=True,
                verbose_name="Statusi",
            ),
        ),
    ]
